### ISSUE TITLE
ansible-galaxy install exception on version check

### ISSUE THREAD

**Issue by rdkr** [nusenu/ansible-relayor#136]
With `requirements.yml` containing `- src: nusenu.relayor`, running `ansible-galaxy install -r requirements.yml -p . -vvv` resulted in the following exception:

```
- downloading role 'relayor', owned by nusenu
https://galaxy.ansible.com/api/v1/roles/?owner__username=nusenu&name=relayor
https://galaxy.ansible.com/api/v1/roles/7630/versions/?page_size=50
ERROR! Unexpected Exception: '<' not supported between instances of 'int' and 'str'
the full traceback was:

Traceback (most recent call last):
  File "/Users/neel/.pyenv/versions/relayor/bin/ansible-galaxy", line 109, in <module>
    exit_code = cli.run()
  File "/Users/neel/.pyenv/versions/3.6.2/envs/relayor/lib/python3.6/site-packages/ansible/cli/galaxy.py", line 138, in run
    self.execute()
  File "/Users/neel/.pyenv/versions/3.6.2/envs/relayor/lib/python3.6/site-packages/ansible/cli/__init__.py", line 149, in execute
    fn()
  File "/Users/neel/.pyenv/versions/3.6.2/envs/relayor/lib/python3.6/site-packages/ansible/cli/galaxy.py", line 387, in execute_install
    installed = role.install()
  File "/Users/neel/.pyenv/versions/3.6.2/envs/relayor/lib/python3.6/site-packages/ansible/galaxy/role.py", line 242, in install
    loose_versions.sort()
  File "/Users/neel/.pyenv/versions/3.6.2/lib/python3.6/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/Users/neel/.pyenv/versions/3.6.2/lib/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by nusenu** [comment]
I'm unable to reproduce this with ansible 2.3.2.0

**Comment by rdkr** [comment]
Quite possibly. I haven't looked into it yet or used ansible-galaxy (before beyond pulling modules), but my initial thought was that perhaps there is some ansible-galaxy config (similar to a setup.py) in which a variable was of the incorrect type. If this isn't an issue which you can reproduce or which is in your control then please close the issue and I can look into it elsewhere. Thanks!

**Comment by nusenu** [comment]
Hi rdkr,
could you add your OS/ansible/python version?
thanks!
